/// Real Arabic-to-English country name mapping, generated directly
/// from csc_picker_plus's own real countries.json data asset (the
/// same real package/dataset backing the country/state/city picker
/// in address_form_screen.dart) -- confirmed this covers all 250 real
/// countries in that dataset, keyed exactly as the package itself
/// returns them when countryStateLanguage is set to
/// CountryStateLanguage.arabic.
///
/// Needed because other real parts of this codebase (the Saudi
/// National Address field's own real detection, and
/// kCountryPhoneCodes's own real phone-code lookup) compare/key by
/// the real ENGLISH country name specifically -- this lets those real
/// checks keep working correctly even when the picker itself is
/// showing (and _selectedCountry itself now holds) the real Arabic
/// name.
const Map<String, String> kArabicToEnglishCountryNames = {
  'أفغانستان': 'Afghanistan',
  'جزر آلاند': 'Aland Islands',
  'ألبانيا': 'Albania',
  'الجزائر': 'Algeria',
  'ساموا الأمريكية': 'American Samoa',
  'أندورا': 'Andorra',
  'أنغولا': 'Angola',
  'أنغويلا': 'Anguilla',
  'القارة القطبية الجنوبية': 'Antarctica',
  'أنتيغوا وباربودا': 'Antigua And Barbuda',
  'الأرجنتين': 'Argentina',
  'أرمينيا': 'Armenia',
  'أروبا': 'Aruba',
  'أستراليا': 'Australia',
  'النمسا': 'Austria',
  'أذربيجان': 'Azerbaijan',
  'جزر البهاما': 'Bahamas The',
  'البحرين': 'Bahrain',
  'بنغلاديش': 'Bangladesh',
  'بربادوس': 'Barbados',
  'بيلاروسيا': 'Belarus',
  'بلجيكا': 'Belgium',
  'بليز': 'Belize',
  'بنين': 'Benin',
  'برمودا': 'Bermuda',
  'بوتان': 'Bhutan',
  'بوليفيا': 'Bolivia',
  'البوسنة والهرسك': 'Bosnia and Herzegovina',
  'بوتسوانا': 'Botswana',
  'جزيرة بوفيه': 'Bouvet Island',
  'البرازيل': 'Brazil',
  'إقليم المحيط الهندي البريطاني': 'British Indian Ocean Territory',
  'بروناي': 'Brunei',
  'بلغاريا': 'Bulgaria',
  'بوركينا فاسو': 'Burkina Faso',
  'بوروندي': 'Burundi',
  'كمبوديا': 'Cambodia',
  'الكاميرون': 'Cameroon',
  'كندا': 'Canada',
  'الرأس الأخضر': 'Cape Verde',
  'جزر كايمان': 'Cayman Islands',
  'جمهورية أفريقيا الوسطى': 'Central African Republic',
  'تشاد': 'Chad',
  'تشيلي': 'Chile',
  'الصين': 'China',
  'جزيرة الكريسماس': 'Christmas Island',
  'جزر كوكوس (كيلينغ)': 'Cocos (Keeling) Islands',
  'كولومبيا': 'Colombia',
  'جزر القمر': 'Comoros',
  'الكونغو': 'Congo',
  'جمهورية الكونغو الديمقراطية': 'Congo The Democratic Republic Of The',
  'جزر كوك': 'Cook Islands',
  'كوستاريكا': 'Costa Rica',
  'ساحل العاج': 'Cote D\'Ivoire (Ivory Coast)',
  'كرواتيا': 'Croatia (Hrvatska)',
  'كوبا': 'Cuba',
  'قبرص': 'Cyprus',
  'جمهورية التشيك': 'Czech Republic',
  'الدنمارك': 'Denmark',
  'جيبوتي': 'Djibouti',
  'دومينيكا': 'Dominica',
  'جمهورية الدومينيكان': 'Dominican Republic',
  'تيمور الشرقية': 'East Timor',
  'الإكوادور': 'Ecuador',
  'مصر': 'Egypt',
  'السلفادور': 'El Salvador',
  'غينيا الاستوائية': 'Equatorial Guinea',
  'إريتريا': 'Eritrea',
  'إستونيا': 'Estonia',
  'إثيوبيا': 'Ethiopia',
  'جزر فوكلاند': 'Falkland Islands',
  'جزر فارو': 'Faroe Islands',
  'جزر فيجي': 'Fiji Islands',
  'فنلندا': 'Finland',
  'فرنسا': 'France',
  'جويانا الفرنسية': 'French Guiana',
  'بولينيزيا الفرنسية': 'French Polynesia',
  'الأراضي الفرنسية الجنوبية': 'French Southern Territories',
  'الغابون': 'Gabon',
  'غامبيا': 'Gambia The',
  'جورجيا': 'Georgia',
  'ألمانيا': 'Germany',
  'غانا': 'Ghana',
  'جبل طارق': 'Gibraltar',
  'اليونان': 'Greece',
  'غرينلاند': 'Greenland',
  'غرينادا': 'Grenada',
  'جزر جوادلوب': 'Guadeloupe',
  'غوام': 'Guam',
  'غواتيمالا': 'Guatemala',
  'غيرنزي وألدرني': 'Guernsey and Alderney',
  'غينيا': 'Guinea',
  'غينيا بيساو': 'Guinea-Bissau',
  'غيانا': 'Guyana',
  'هايتي': 'Haiti',
  'جزيرة هيرد وجزر ماكدونالد': 'Heard Island and McDonald Islands',
  'هندوراس': 'Honduras',
  'هونغ كونغ': 'Hong Kong S.A.R.',
  'المجر': 'Hungary',
  'أيسلندا': 'Iceland',
  'الهند': 'India',
  'إندونيسيا': 'Indonesia',
  'إيران': 'Iran',
  'العراق': 'Iraq',
  'أيرلندا': 'Ireland',
  'إسرائيل': 'Israel',
  'إيطاليا': 'Italy',
  'جامايكا': 'Jamaica',
  'اليابان': 'Japan',
  'جيرسي': 'Jersey',
  'الأردن': 'Jordan',
  'كازاخستان': 'Kazakhstan',
  'كينيا': 'Kenya',
  'كيريباتي': 'Kiribati',
  'كوريا الشمالية': 'Korea North',
  'كوريا الجنوبية': 'Korea South',
  'الكويت': 'Kuwait',
  'قيرغيزستان': 'Kyrgyzstan',
  'لاوس': 'Laos',
  'لاتفيا': 'Latvia',
  'لبنان': 'Lebanon',
  'ليسوتو': 'Lesotho',
  'ليبيريا': 'Liberia',
  'ليبيا': 'Libya',
  'ليختنشتاين': 'Liechtenstein',
  'ليتوانيا': 'Lithuania',
  'لوكسمبورغ': 'Luxembourg',
  'ماكاو': 'Macau S.A.R.',
  'مقدونيا': 'Macedonia',
  'مدغشقر': 'Madagascar',
  'ملاوي': 'Malawi',
  'ماليزيا': 'Malaysia',
  'جزر المالديف': 'Maldives',
  'مالي': 'Mali',
  'مالطا': 'Malta',
  'جزيرة مان': 'Man (Isle of)',
  'جزر مارشال': 'Marshall Islands',
  'مارتينيك': 'Martinique',
  'موريتانيا': 'Mauritania',
  'موريشيوس': 'Mauritius',
  'مايوت': 'Mayotte',
  'المكسيك': 'Mexico',
  'ميكرونيزيا': 'Micronesia',
  'مولدوفا': 'Moldova',
  'موناكو': 'Monaco',
  'منغوليا': 'Mongolia',
  'الجبل الأسود': 'Montenegro',
  'مونتسرات': 'Montserrat',
  'المغرب': 'Morocco',
  'موزمبيق': 'Mozambique',
  'ميانمار': 'Myanmar',
  'ناميبيا': 'Namibia',
  'ناورو': 'Nauru',
  'نيبال': 'Nepal',
  'بونير، سينت أوستاتيوس وسابا': 'Bonaire, Sint Eustatius and Saba',
  'هولندا': 'Netherlands The',
  'كاليدونيا الجديدة': 'New Caledonia',
  'نيوزيلندا': 'New Zealand',
  'نيكاراغوا': 'Nicaragua',
  'النيجر': 'Niger',
  'نيجيريا': 'Nigeria',
  'نييوي': 'Niue',
  'جزيرة نورفولك': 'Norfolk Island',
  'جزر ماريانا الشمالية': 'Northern Mariana Islands',
  'النرويج': 'Norway',
  'عمان': 'Oman',
  'باكستان': 'Pakistan',
  'بالاو': 'Palau',
  'فلسطين': 'Palestine',
  'بنما': 'Panama',
  'بابوا غينيا الجديدة': 'Papua new Guinea',
  'باراغواي': 'Paraguay',
  'بيرو': 'Peru',
  'الفلبين': 'Philippines',
  'جزيرة بيتكيرن': 'Pitcairn Island',
  'بولندا': 'Poland',
  'البرتغال': 'Portugal',
  'بورتوريكو': 'Puerto Rico',
  'قطر': 'Qatar',
  'ريونيون': 'Reunion',
  'رومانيا': 'Romania',
  'روسيا': 'Russia',
  'رواندا': 'Rwanda',
  'سانت هيلينا': 'Saint Helena',
  'سانت كيتس ونيفيس': 'Saint Kitts And Nevis',
  'سانت لوسيا': 'Saint Lucia',
  'سان بيير وميكلون': 'Saint Pierre and Miquelon',
  'سانت فينسنت والغرينادين': 'Saint Vincent And The Grenadines',
  'سانت بارتيليمي': 'Saint-Barthelemy',
  'سانت مارتن (الجزء الفرنسي)': 'Saint-Martin (French part)',
  'ساموا': 'Samoa',
  'سان مارينو': 'San Marino',
  'ساو تومي وبرينسيبي': 'Sao Tome and Principe',
  'المملكة العربية السعودية': 'Saudi Arabia',
  'السنغال': 'Senegal',
  'صربيا': 'Serbia',
  'سيشيل': 'Seychelles',
  'سيراليون': 'Sierra Leone',
  'سنغافورة': 'Singapore',
  'سلوفاكيا': 'Slovakia',
  'سلوفينيا': 'Slovenia',
  'جزر سليمان': 'Solomon Islands',
  'الصومال': 'Somalia',
  'جنوب أفريقيا': 'South Africa',
  'جورجيا الجنوبية': 'South Georgia',
  'جنوب السودان': 'South Sudan',
  'إسبانيا': 'Spain',
  'سريلانكا': 'Sri Lanka',
  'السودان': 'Sudan',
  'سورينام': 'Suriname',
  'سفالبارد وجان ماين': 'Svalbard And Jan Mayen Islands',
  'سوازيلاند': 'Swaziland',
  'السويد': 'Sweden',
  'سويسرا': 'Switzerland',
  'سوريا': 'Syria',
  'تايوان': 'Taiwan',
  'طاجيكستان': 'Tajikistan',
  'تنزانيا': 'Tanzania',
  'تايلاند': 'Thailand',
  'توغو': 'Togo',
  'توكيلاو': 'Tokelau',
  'تونغا': 'Tonga',
  'ترينيداد وتوباغو': 'Trinidad And Tobago',
  'تونس': 'Tunisia',
  'تركيا': 'Turkey',
  'تركمانستان': 'Turkmenistan',
  'جزر تركس وكايكوس': 'Turks And Caicos Islands',
  'توفالو': 'Tuvalu',
  'أوغندا': 'Uganda',
  'أوكرانيا': 'Ukraine',
  'الإمارات العربية المتحدة': 'United Arab Emirates',
  'المملكة المتحدة': 'United Kingdom',
  'الولايات المتحدة': 'United States',
  'جزر الولايات المتحدة البعيدة الصغرى': 'United States Minor Outlying Islands',
  'أوروغواي': 'Uruguay',
  'أوزبكستان': 'Uzbekistan',
  'فانواتو': 'Vanuatu',
  'دولة الفاتيكان': 'Vatican City State (Holy See)',
  'فنزويلا': 'Venezuela',
  'فيتنام': 'Vietnam',
  'جزر العذراء البريطانية': 'Virgin Islands (British)',
  'جزر العذراء الأمريكية': 'Virgin Islands (US)',
  'واليس وفوتونا': 'Wallis And Futuna Islands',
  'الصحراء الغربية': 'Western Sahara',
  'اليمن': 'Yemen',
  'زامبيا': 'Zambia',
  'زيمبابوي': 'Zimbabwe',
  'كوسوفو': 'Kosovo',
  'كوراساو': 'Curaçao',
  'سينت مارتن (الجزء الهولندي)': 'Sint Maarten (Dutch part)',
};

/// Real, small convenience -- normalizes a real country name that may
/// be in either real language back to English, falling back to the
/// real original value unchanged if it's not a real recognized
/// Arabic country name (i.e. it was already English, or is null/empty).
String normalizeCountryNameToEnglish(String? country) {
  if (country == null) return '';
  return kArabicToEnglishCountryNames[country] ?? country;
}
